name: CI

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.11.0
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.11.0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('yarn.lock') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: yarn install

      - name: Run formatting checks
        run: yarn format-check

      - name: Run linting checks
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Buid
        run: yarn build
