name: Release Insiders

on:
  push:
    branches:
      - master
      - feat-add-npm-publish-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.11.0
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.11.0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('yarn.lock') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
        env:
          CI: true

      - name: Run formatting checks
        run: yarn format-check

      - name: Run linting checks
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Resolve version
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: 'Version based on commit: 0.0.0-beta.${{ steps.vars.outputs.sha_short }}'
        run: npm version 0.0.0-beta.${{ steps.vars.outputs.sha_short }} --force --no-git-tag-version

      - name: Publish
        run: npm publish --tag beta
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
